global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'data-shift-monitor'
    static_configs:
      - targets: ['data-shift-monitor:8081']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
