apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://vllm:8000/metrics
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      timeInterval: 30s
